driver:
  name: docker

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    driver_config: 
      socket: <%= ENV['DOCKER_HOST'] %>

suites:
  - name: default
    run_list: github_users::default
    attributes:
      github_users:
        users:
        - dustinmm80