driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 11.10.0

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list: github_users::default
    attributes:
      github_users:
        users:
        - dustinmm80