before_install:
  - wget https://opscode-omnibus-packages.s3.amazonaws.com/debian/6/x86_64/chefdk_0.3.0-1_amd64.deb
  - sudo dpkg -i chefdk_0.3.0-1_amd64.deb

before_script:
  - chef shell-init bash

script:
  - foodcritic .
